name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secretes.ACCESS_TOKEN }}
        BRANCH: develop
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
