name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - develop
jobs:
  pre:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
  test:
    runs-on: ubuntu-18.04
    needs: pre
    steps:
    - name: List files
      run: ls
    - name: Test Unit
      run: npm run test:unit
  build-and-deploy:
    runs-on: ubuntu-18.04
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy
      run: |
        npm install
        npm run build
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: develop
