name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - develop
      - ci
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Test Unit
      run: |
        npm install
        npm run test:unit
  build-and-deploy:
    runs-on: ubuntu-18.04
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy
      run: |
        npm install
        npm run build:prod
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: develop
