name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Test Unit
        run: npm run test:unit
  build-and-deploy:
    runs-on: ubuntu-18.04
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: develop
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
